# Generated by Django 2.0.6 on 2018-10-19 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('hit', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(auto_now=True)),
                ('group_no', models.IntegerField(default=1)),
                ('order_no', models.IntegerField(default=1)),
                ('depth', models.IntegerField(default=0)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
