# Generated by Django 2.0.6 on 2018-10-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
    ]
